[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "deeplscalp-project"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = []

[tool.setuptools]
packages = {find = {where = ["."]}}

[tool.setuptools.package-dir]
"" = "."
